-- 코드를 작성해주세요

SELECT * FROM
(SELECT  
    YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    B.MAX_COLONY_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, 
    ID 
    FROM ECOLI_DATA A,
    (SELECT DATE_FORMAT(DIFFERENTIATION_DATE,'%Y') AS YEAR_2, 
     MAX(SIZE_OF_COLONY) AS MAX_COLONY_SIZE 
     FROM ECOLI_DATA 
     GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE,'%Y')) B
 WHERE DATE_FORMAT(A.DIFFERENTIATION_DATE,'%Y') = B.YEAR_2) C
 ORDER BY C.YEAR, C.YEAR_DEV