-- 코드를 작성해주세요

SELECT  ID ,(SELECT FISH_NAME FROM FISH_NAME_INFO WHERE FISH_TYPE = A.FISH_TYPE) AS FISH_NAME, B.LENGTH  
FROM FISH_INFO A , 
(SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) B
WHERE A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH

